[package]
name = "focus"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
colored = "3.1.1"
ctrlc = "3.5.1"
daemonize = "0.5.0"
gag = "1.0.0"
rodio = "0.21.1"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.11"
